config/routes.rb
Rails.application.routes.draw do

  get 'items/index'

  get 'items/new'

  get 'items/show'

  get 'items/edit'

  get 'sessions/new'

    get root 'general_pages#index'
    
    resources :users 
    
    resources :items
    
    resources :vegetables
    
    resources :fruits
    
    resources :juices
    
    get      '/faq',             to:  'faq#general_pages'
    
    get      '/help',            to:  'help#general_pages'
    
    get      '/about',           to:  'about#general_pages'

    get      '/cart',            to:  'carts#index'
    
    get      '/clearcart',       to:  'carts#clearcart'

    get      '/cart/:id',        to:  'carts#add'
    
    get      '/question',        to:  'items#questions'
    
    get      '/recommendation',  to:  'items#recommendations'
    
    get      '/juice_table',     to:  'items#table'
    
    get      '/login',           to:  'sessions#new'
    
    post     '/login',           to:  'sessions#create'
    
    get      '/logout',          to:  'sessions#destroy'
    
    get      '/store',           to:  'general_pages#store'
    
    get      '/sort',            to:  'items#sort'   
    
#    get     '/search',          to:  'items#search'

    
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
#  The following code was taken from a helpful video
#  tutorial by Youtuber Martins Tutorials. The 
#  video is part of a series of five videos
#  on how to implement cart functionality into
#  a Rails application. The video is titled
#  Ruby on Rails Shopping Cart Tutorial Adding Cart Logic 4
#  Scource:  https://www.youtube.com/watch?v=WRVwfVUaj_Y

    
        def clearcart
          session[:cart] = nil
          redirect_to cart_path
        end
    
    
    def add
        id = params[:id]
      if session[:cart] then
        cart = session[:cart]
      else
        session[:cart] = {}
        cart = session[:cart]
      end
      
      if cart[id] then
        cart[id] = cart[id] + 1
      else
        cart[id] = 1
      end
      redirect_to :action => :index
      
    end

    
    def index
         if session[:cart] then
           @cart = session[:cart]
         else
           @cart = {}
         end
    end

end

app/helpers/carts_helper.rb
module CartsHelper
    
    def cart_empty?
        return true if session[:cart].nil?
    end
    
end

app/views/carts/index.html.erb
<div class="row">
    <div class="col-xs-4 col-xs-offset-4 cart-box">
    
        <div class="col-xs-12">
            <h3 class="fancy-title">
                Your Cart
            </h3>
        </div>
        
        <div class="row">
            <div class="col-xs-12">
                <%= @cart.each do |id, quantity| %>
                    <% item = Item.find_by_id(id)%>
                    <p>
                        You have <%= quantity.to_s %> of the item '
                        <%= item.title %>' your cart.
                    </p>
                <% end %>

            </div>
        </div>
        
        <hr style="border-color:#3b2e18"/>
        <%= link_to 'Back to store', items, class: 'pull-left' %>
        <%= link_to 'clear cart', clearcart_path, class: 'pull-right' %>
    </div>
    
</div>