config/routes.rb
Rails.application.routes.draw do

  get 'items/index'

  get 'items/new'

  get 'items/show'

  get 'items/edit'

  get 'sessions/new'

    get root 'general_pages#index'
    
    resources :users 
    
    resources :items
    
    resources :vegetables
    
    resources :fruits
    
    resources :juices
    
    get      '/faq',             to:  'faq#general_pages'
    
    get      '/help',            to:  'help#general_pages'
    
    get      '/about',           to:  'about#general_pages'

    get      '/cart',            to:  'carts#index'
    
    get      '/clearcart',       to:  'carts#clearcart'

    get      '/cart/:id',        to:  'carts#add'
    
    get      '/question',        to:  'items#questions'
    
    get      '/recommendation',  to:  'items#recommendations'
    
    get      '/juice_table',     to:  'items#table'
    
    get      '/login',           to:  'sessions#new'
    
    post     '/login',           to:  'sessions#create'
    
    get      '/logout',          to:  'sessions#destroy'
    
    get      '/store',           to:  'general_pages#store'
    
    get      '/sort',            to:  'items#sort'   
    
#    get     '/search',          to:  'items#search'

    
    
end

app/models/item.rb
class Item < ApplicationRecord
    
    validates :terms_of_service, acceptance: true
    
    
    

    def self.search(search)
            self.where('title LIKE ?', "%#{search}%")
    end
    
    
#   Methods for catergory-filtering
    def self.juicesOnly
        self.where('catergory = ?', 'Juice').order(title: "asc")
    end
    
    def self.veggieOnly
        self.where('catergory = ?', 'Vegetable').order(title: "asc")
    end
    
    def self.fruitsOnly
        self.where('catergory = ?', 'Fruit').order(title: "asc")
    end
    
    
#   Method for sorting price
    def self.sort_price
        self.where('catergory = ?', "#{params[sort]}").order(price: 'asc')
    end

#   Method for sorting high fat juices
    def self.sort_low_fat
        self.where('catergory = ?', 'Juice').order(fat_level: "asc")
    end
    
#   Method for sorting no nuts-containing juices
    def self.sort_no_nuts
        self.where('catergory = ?', 'Juice').order(contains_nuts: "asc")
    end
    
#   Method for sorting low sugar juices
    def self.sort_low_sugar
        self.where('catergory = ?', 'Juice').order(sugar_comtent: "asc")
    end
    
#   Method for finding a unknown title
    def self.find_unknown(unknown)
        self.find_by(title:("#{unknown}"))
    end
    

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item = Item.paginate(page: params[:page], per_page: 9)
    if params[:search]
      @item = Item.search(params[:search]).paginate(page: params[:page],
              per_page: 9)
    end
    if params[:filter]
      @item = Item.search(params[:search]).paginate(page: params[:page],
              per_page: 9).order(price: 'asc')
    end
    if params[:sort] && params[:sort] == 'juices'
      @item = Item.paginate(page: params[:page], per_page: 9).juicesOnly
    elsif params[:sort] && params[:sort] == 'vegetables'
       @item = Item.paginate(page: params[:page], per_page: 9).veggieOnly
    elsif params[:sort] && params[:sort] == 'fruits'
      @item = Item.paginate(page: params[:page], per_page: 9).fruitsOnly
    end
    if params[:sort] && params[:sort] == 'juices' && params[:filter] &&
       params[:filter] == 'low fat'
       @item = Item.search(params[:search]).paginate(page: params[:page],
              per_page: 9).sort_low_fat
    elsif params[:sort] && params[:sort] == 'juices' && params[:filter] &&
          params[:filter] == 'no nuts'
          @item = Item.paginate(page: params[:page], per_page: 9).sort_no_nuts
    elsif params[:sort] && params[:sort] == 'juices' && params[:filter] &&
          params[:filter] == 'low sugar'
          @item = Item.paginate(page: params[:page], per_page: 9).sort_low_sugar
    end
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end
  
  def create
    @item = Item.new(items_params)
    @item.save
    if @item.save
      flash[:success] = 'This item has been successfully saved to the database.'
      redirect_to items_path
    else
      flash[:danger] = 'Failed save'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
        if @item.update(items_params)
            flash[:success] = "#{@item.title} has been successfully updated."
            redirect_to items_path
        else
            flash[:danger] = "Invalid information entered"
            render 'edit'
        end
        
  end
  
  
  def questions
  end
  
  def recommendations
    
    @myTitleList = []
    @mySugarContentList = []
    @myFatLevelList = []
    
    
    @item = Item.juicesOnly
    
     @item.each do |item|
      @myTitleList << "#{item.title}"
      @mySugarContentList << "#{item.sugar_comtent}"
      @myFatLevelList << "#{item.fat_level}"
    end
  
  remove_high_fat(params[:Q3], @myTitleList)
  remove_nuts(params[:Q2], @myTitleList)
  remove_high_protein(params[:Q1], @myTitleList)
  
  end
  
  def sort
    @item = Item.sort('price')
  end


  def table
    @item = Item.all
  end
  

  
  
  
  
  
  
  
  
  private
        def items_params
            params.require(:item).permit(:title, :price, :sugar_comtent,
            :contains_nuts, :mixture, :fat_level, :description, 
            :catergory, :url, :url1, :url_2, :url_3, :url_4,
            :valueCalories, :valueFatCalories, :valueTotalFat,
            :valueSatFat, :valueTransFat, :valueCholesterol, :valueSodium,
            :valueTotalCarb, :valueFibers, :valueSugars, :valueProteins,
            :valueVitaminA, :valueVitaminC, :valueCalcium, :valueIron, 
            :ingredients, :protein_level)
        end
  
end

app/helpers/items_helper.rb
module ItemsHelper
    
    def sort_out 
       
    end
    
    
#   For Question 1: Code that will remove high-protein juices
    def remove_high_protein(userAns, juiceList)
        if userAns == 'No'
            @juice = Item.juicesOnly
            @juice.each do |juice|
                if juice.protein_level > 3
                    z = juice.title
                    juiceList.delete(z)
                end
                end
        end
    end

#   For Question 2: Code that will remove nut-containing juices
    def remove_nuts(userAns, juiceList)
        if userAns == 'Yes'
            @juice = Item.juicesOnly
            @juice.each do |juice|
                if juice.contains_nuts == true
                    z = juice.title
                    juiceList.delete(z)
                end
                end
        end
    end


#   For Question 3: Code that will remove high-fat level juices
    def remove_high_fat(userAns, juiceList)
        if userAns == 'Yes'
            @juice = Item.juicesOnly
            @juice.each do |juice|
                if juice.fat_level > 3
                    z = juice.title
                    juiceList.delete(z)
                    @juice.find_unknown(z).price
                end
                end
        end
    end
    
    def title_price(itobj)
        itobj.title + " - €#{itobj.price}"
    end
end

app/views/items/index.html.erb
<%= provide(:title, 'Store - Items') %>

<div class=" col-md-12">
  <h3 class="main-headings"> 
    Come and Browse <br />
      <small>
        Fruits, vegetables and Juices
      </small>
  </h3>
  
  
  <!-- Search Bar -->
  <div class="row">
      <div class="col-md-6 col-xs-8">
        <div class="col-xs-10">
          <%= form_tag items_path, :method => 'get' do %>
          
              <%= text_field_tag :Search, params[:search],
                              name: 'search',
                              placeholder: 'Search Vegetables',
                              class: 'search-box' %>
        </div>
        <div class="col-xs-2">
            <%= submit_tag :Search, :name => nil, class: 'btn btn-success btn-lg' %>
        </div>
        <% end %>
      </div>
</div>
  
</div>


<!-- Item-filter menu -->
<div class="row">
  <div class="col-xs-12">
       <%= render 'layouts/store_items' %>
   </div>
</div>

<div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <%= will_paginate @item %>
    </div>
</div>


<!-- The following code is for each item displayed -->
<div class="row">

    <div class="col-xs-12 col-md-9 col-lg-9">
      <% @item.each do |item| %>
        <div class="col-xs-12 col sm-3 col-md-3 col-lg-4 item-container">
            <p>
              <%= link_to title_price(item), '#', class: 'fancy-title' %> 
            </p>
            <br />
              <%= link_to image_tag(item.url, alt: 'product image',
                                                    class: 'img-index'),
                                                    item_path(item.id) %>

            <div class="row">
              <div class="col-xs-12">
                  <nav class="navbar navbar-default">
                      <ul class="nav nav-pills nav-stacked">
                        <li> 
                            <%= link_to 'Add to Cart', "/cart/#{item.id}", class: 'small-links' %>  
                        </li>
                        <% if logged_in? %>
                            <li> <%= link_to 'Edit', edit_item_path(item), 
                                                     class: 'small-links'  %> 
                            </li>
                        <% end %>
                      </ul>
                  </nav>
                </div>
                
                
<!-- Only adminastrator can see this table -->
                <% if logged_in? && current_user.admin? %>
                      <div class="row">
                          <div class="col-xs-12">
                              <table class="table tiny-font">
                                <tr>
                                  <th> Fat Level  </th>
                                  <th> Sugar Content  </th>
                                  <th> Contains Nuts  </th>
                                  <th> Protein Level  </th>
                                </tr>
                                
                                  <td> <%= item.fat_level %> </td>
                                  <td> <%= item.sugar_comtent %> </td>
                                  <td> <%= item.contains_nuts %> </td>
                                  <td> <%= item.protein_level %> </td>
      
                              </table>
                          </div>
                      </div>
                <% end %>
            </div>
            
        </div>
      <% end %>
    </div>
    
    
<!-- Recommendation Sectiion -->
    <div class="col-xs-12 com-md-4 col-lg-2">
      <div class="rec-sect">
        <p class="main-headings">
          Want a recommendation?
        </p>
        <p class="normal-para">
          Not sure what the right food is for you? Don't worry, we
          have experts at hand to help you deciede.
        </p>
        <div>
            <p>
              <h1> 3
                <small style="font-size: 40px;"> 
                  questions</small>
              </h1>
              <p style="font-size: 25px; margin-top: -15px;">
                That's all it takes
              </p>
              <p>
                With just three answers to our simple questions about your food
                preferences, we can recommend a mixed fruit and vegetable juice!
                <br />
                <br />
                <span>Tailored to your needs!</span>
              </p>
              <p class=>
                If your interested, just <%= link_to 'click here', question_path %>
                and within a jiffy we'l have your ideal mix!
              </p>
            </p>
        </div>
      </div>
    </div>
    
</div>

<div class="row">
    <div class="col-xs-4 col-xs-offset-4">
        <%= will_paginate @item %>
    </div>
    

</div>

app/views/items/questions.html.erb
<div class="row">
    <div class="col-xs-12">
        
        
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4 fancy-title text-center">
                Three Short Questions
                <hr style="border-color: #3b2e18" />
            </div>
        </div>
        
        <%= form_tag recommendation_path, :method => 'get' do %>
        
        <div class="row">
            <div class="col-xs-4 text-center">
                <h3 class="numer-title"> 1 </h3>
            </div>
            <div class="col-xs-4 text-center">
                <h3 class="numer-title"> 2 </h3>
            </div>
            <div class="col-xs-4 text-center">
                <h3 class="numer-title"> 3 </h3>
            </div>
        </div>
        
        <div class="row">
            <!-- Question One -->
            <div class="col-xs-4">
               <center>
                     <h3> Do you prefer a high-protein juice? </h3> 
                </center>
                <br />
                <center>
                    <div class="form-group">
                        <%= radio_button_tag(:Q1, 'Yes') %>
                        <%= label_tag(:Q1_strength, 'I want to a high-protein
                                                     juice') %>
                    </div>
                    <div class="form-group">
                        <%= radio_button_tag(:Q1, 'No') %>
                        <%= label_tag(:Q1_waight, 'I want a low-protein juice') %>
                    </div>
                </center>
            </div>  
            
            <!-- Question Two -->
            <div class="col-xs-4">
               <center>
                     <h3> Are you allergic to nuts? </h3> 
                </center>
                <br />
                <center>
                    <div class="form-group">
                        <%= radio_button_tag(:Q2, 'Yes') %>
                        <%= label_tag(:Q2_strength, 'I am allergic to nuts') %>
                    </div>
                    <div class="form-group">
                        <%= radio_button_tag(:Q2, 'No') %>
                        <%= label_tag(:Q2_waight, 'I am not allergic to nuts') %>
                    </div>
                </center>
            </div> 
            
            <!-- Question Three -->
            <div class="col-xs-4">
               <center>
                     <h3> Do you prefer your juice to be low-fat? </h3> 
                </center>
                <br />
                <center>
                    <div class="form-group">
                        <%= radio_button_tag(:Q3, 'Yes') %>
                        <%= label_tag(:Q3_yes, 'I would like my juice to
                                                be low-fat') %>
                    </div>
                    <div class="form-group">
                        <%= radio_button_tag(:Q3, 'No') %>
                        <%= label_tag(:Q3_no, 'I do not mind') %>
                    </div>
                </center>
            </div> 

        </div>
        
        <div class="row">
             <div class="col-xs-4 col-xs-offset-4">
                     <%= submit_tag :Finished, class: "btn btn-lg btn-success,
                                                       center-block" %>
             </div>
        </div>
        
        <% end %>
        
                            

app/views/items/recommendations.html.erb
    <div class="row">
        <div class="col-xs-4">
            <%= for a in 0..@myTitleList.count do %>
            
              <h5> Title: <%= @myTitleList[a] %>  <br>
                   Sugar Content: <%=@mySugarContentList[a] %> <br />
                   Fat Level: <%= @myFatLevelList[a] %> 
                   </h5>
                   <%= a +=1 %>
                   
            <% end %>
        </div>
         
                  <div class="col-xs-4">
                      <%= for x in @myTitleList do %>
                      <div class="row">
                          <div class="col-xs-12 recommend-container">
                              <h4 class='text-center'>
                                  We Recommend: <br />
                                  <%= "#{x}" %>
                                  
                              </h4>
                               <% g = Item.find_by(title: x) %>
                               <%= image_tag "#{g.url}", alt: 'hello',
                                   class: 'img-small center-block'%>
                          </div>
                      </div>
                      <% end %>
                  </div>
<% if logged_in? && current_user.admin? %>
    <%= @myHash %>  
<% end %>
     </div>           

app/views/items/show.html.erb
<div class="row">
    <div class="col-xs-10">
        
        <div class="row">
            <div class="col-xs-8">
                <nav>
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a> Pictures </a>
                        </li>
                        <li>
                            <a id="nutrition-tab"> Nutrition Information </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        
        
        
        <div class="row">
            
            <div class="col-xs-8">
                <div style= "height: 375px;">
                    
                    <%= image_tag(@item.url, alt: 'product image',
                                               class: 'img-borders',
                                               id: 'lg-img') %>
                </div>
            </div>
            
            
<!-- Side item photos and nutritional information -->
            <div class="col-xs-3" id="side-container">
                
                <div class="row">
                    <div class="col-xs-12">
                        <div style=" height: 125px;">
                            <%= image_tag(@item.url_2, 
                                           alt: 'product image',
                                           class: 'img-small',
                                           id: 'sm_img_1') %>
                       </div>
                   </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-12">
                        <div style=" height: 125px;">
                            <%= image_tag(@item.url_3, 
                                           alt: 'product image',
                                           class: 'img-small',
                                           id: 'sm_img_2') %>
                        </div>
                    
                </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-12">
                        <div style=" height: 125px;">
                            <%= image_tag(@item.url_4, 
                                           alt: 'product image',
                                           class: 'img-small',
                                           id: 'sm_img_3') %>
                       </div>
                    
                </div>
                </div>
            </div>
            
        </div>
        
        
        <div class="row">
            <div class="col-xs-12">
                <h2 class="fancy-title"> <%= @item.title %> - 
                                         <%= @item.price %>
                </h2>
            </div>
        </div>
        
        
        <div class="row">
            <div class="col-xs-8">

                
                <p class="veg-des">
                    <%= @item.description %>
                </p>
            </div>
            
            
            <div class="col-xs-4">
                <nav>
                    <ul class="nav nav-pills nav-stacked">
                        <li>
                            <%=link_to 'Add to cart', cart_path %>
                            <% if logged_in? %>
                                <%= link_to 'Edit', edit_item_path %>
                            <% end %>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

        
<!-- Nutrition Label -->
        <div class="row">
            <div class="col-xs-3">
                <did id="test1">
               </div>
        </div>  

       
    </div>
</div>



<script>

/* The following function is a Jquery plugin
   titled Nutrition-Label by Github user Nutritionix.
   The purpose of this function is to create a 
   nutrition label template, which dispays statitics
   about a product.
   Scoure: https://github.com/nutritionix/nutrition-label
*/
    
    $('#test1').nutritionLabel({
	'showServingUnitQuantity' : false,
	'itemName' : '<%= @item.title %>',
	'ingredientList' : 'Bleu Cheese Dressing',

	'showPolyFat' : false,
	'showMonoFat' : false,

	'valueCalories' : '<%= @item.valueCalories %>',
	'valueFatCalories' : '<%= @item.valueFatCalories %>',
	'valueTotalFat' : '<%= @item.valueTotalFat %>',
	'valueSatFat' : '<%= @item.valueSatFat %>',
	'valueTransFat' : '<%= @item.valueTransFat %>',
	'valueCholesterol' : '<%= @item.valueCholesterol %>',
	'valueSodium' : '<%= @item.valueSodium %>',
	'valueTotalCarb' : '<%= @item.valueTotalCarb %>',
	'valueFibers' : '<%= @item.valueFibers %>',
	'valueSugars' : '<%= @item.valueSugars %>',
	'valueProteins' : '<%= @item.valueProteins %>',
	'valueVitaminA' : '<%= @item.valueVitaminA %>',
	'valueVitaminC' : '<%= @item.valueVitaminC %>',
	'valueCalcium' : '<%= @item.valueCalcium %>',
	'valueIron' : '<%= @item.valueIron %>'
});


$(document).ready(function() {

    
    
//    Source-change for small image 1 when mouse rolls over 
         $('#sm_img_1').on("mouseenter", function() {
            $('#lg-img').fadeOut(300, function(){
                $('#lg-img').attr( {src: "<%= asset_path @item.url_2 %>"} ).bind('onreadystatechange load', function(){
                   if (this.complete) $(this).fadeIn(300);
                });
            });
         });
//    Source-change for small image 2 when mouse rolls over 

          $('#sm_img_2').on("mouseenter", function() {
            $('#lg-img').fadeOut(300, function(){
                $('#lg-img').attr( {src: "<%= asset_path @item.url_3 %>"} ).bind('onreadystatechange load', function(){
                   if (this.complete) $(this).fadeIn(300);
                });
            });
         });
//    Source-change for small image 3 when mouse rolls over 

         $('#sm_img_3').on("mouseenter", function() {
            $('#lg-img').fadeOut(300, function(){
                $('#lg-img').attr( {src: "<%= asset_path @item.url_4 %>"} ).bind('onreadystatechange load', function(){
                   if (this.complete) $(this).fadeIn(300);
                });
            });
         });
         
    $('.img-small').mouseleave(function() {
        $('#lg-img').fadeOut(300, function(){
           $('#lg-img').attr({src: "<%= asset_path @item.url %>"}).bind('onreadystatechange load', function(){
              if (this.complete) $(this).fadeIn(300);
           });
        });
    });
});


</script>

app/views/items/table.html.erb
<div class="row">
    
    <div class="col-xs-4 col-xs-offset-4">
         <center> <h3> Juice Mix List </h3> </center>
    </div>
            
    <div class="col-xs-12">
        <%= render 'layouts/juice_list' %>
    </div>
</div>