config/routes.rb
Rails.application.routes.draw do

  get 'items/index'

  get 'items/new'

  get 'items/show'

  get 'items/edit'

  get 'sessions/new'

    get root 'general_pages#index'
    
    resources :users 
    
    resources :items
    
    resources :vegetables
    
    resources :fruits
    
    resources :juices
    
    get      '/faq',             to:  'faq#general_pages'
    
    get      '/help',            to:  'help#general_pages'
    
    get      '/about',           to:  'about#general_pages'

    get      '/cart',            to:  'carts#index'
    
    get      '/clearcart',       to:  'carts#clearcart'

    get      '/cart/:id',        to:  'carts#add'
    
    get      '/question',        to:  'items#questions'
    
    get      '/recommendation',  to:  'items#recommendations'
    
    get      '/juice_table',     to:  'items#table'
    
    get      '/login',           to:  'sessions#new'
    
    post     '/login',           to:  'sessions#create'
    
    get      '/logout',          to:  'sessions#destroy'
    
    get      '/store',           to:  'general_pages#store'
    
    get      '/sort',            to:  'items#sort'   
    
#    get     '/search',          to:  'items#search'

    
    
end

app/views/layouts/_account_summery.html.erb
<div>
    <h3> Your Account </h3>
    
    <%= @current_user.name %>
    
    <%= @current_user.email %>
    
    <%= link_to 'Change account details?', edit_user_path %>
</div>

app/views/layouts/_banner.html.erb
    <div class="banner-image">
        <div class="title-overlay">
            <h1 class="banner-title"> Explore  </h1>
        </div>
        <h1 class="banner-title-2"> Nature </h1>
    </div>

app/views/layouts/_footer.html.erb
<div class="row footer-class">
    <div class="col-xs-12">
        <div class="col-xs-4" style="border-right: 1px solid #f6eaca">
            <h5> Need to get in touch? </h5>
            <p style="font-size: 12px">
                You can contact us by these methods:
                <br />
                Email: naturewell@gmail.ie
                <br />
                Phone Number: 071643231
                <br />
                Address: Talbot Street, <br />
                         Dublin City, <br />
                         Ireland
                
            </p>
        </div>
        <div class="col-xs-4" style="border-right: 1px solid #f6eaca">
            <h5> Need Help? </h5>
            <p style="font-size: 12px">
                These links provide information in relation to who
                we are and what we do.
                <br />
                <div class="col-xs-4">
                    <%= link_to 'About', about_path %> <br /> 
                </div>
                 <div class="col-xs-4">
                    <%= link_to 'Help', help_path %> <br />
                </div>
                <div class="col-xs-4">
                    <%= link_to 'FAQ', faq_path %> <br />
                </div>
            </p>
        </div>
        <div class="col-xs-4" style="border-right: 1px solid #f6eaca">
            <h5> Follow us on social media <br />
                <small>
                    And keep up to date with us
                </small>
                <br />
                <br />
                <div class="col-xs-4">
                    <%= image_tag('facebook_icon.png',
                                  alt: 'facebook icon',
                                  class: 'icon-size') %>
                </div>
                <div class="col-xs-4">
                    <%= image_tag('twitter_icon.png',
                                  alt: 'facebook icon',
                                  class: 'icon-size') %>
                </div>
                <div class="col-xs-4">
                    <%= image_tag('instagram_icon.png',
                                  alt: 'facebook icon',
                                  class: 'icon-size') %>
                </div>
            </h5>
            
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<row>
    <div class="col-lg-12" style="background-color: #f6eaca;">
        <nav class="navbar" stlye="margin-top: 20px; border-bottom: 1px rigid #3b2e18">
            <ul class="nav nav-pills nav-justified large-links">
                <li>
                    <%= link_to 'Home', root_url %>
                </li>
                <li>
                    <%= link_to 'Store', items_path %>
                </li>
                <li>
                    <%= link_to 'Recommendation', question_path %>
                </li>
                <li>
                    <a href="#"> Help </a>
                </li>
            </ul>
        </nav>
        
        <hr style="border-color:#3b2e18"/>
        
    </div>
</row>

app/views/layouts/_juice_list.html.erb
<div class="row">
    
    <div class="row">
        <div class="col-xs-12">
            
            <table class="table tiny-font">
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Sugar Content
                    </th>
                    <th>
                        Fat Level
                    </th>
                    <th>
                        Contains Nuts
                    </th>
                    <th>
                        Mixture
                    </th>
                    <th>
                        Ingredients
                    </th>
                    <th>
                        Catergory
                    </th>
                
                    <% @item.each do |item| %>
                        <% if item.catergory == 'Juice'%>
                        
                            <tr>
                                <td>
                                   <%= item.title %>
                                </td> 
                                <td>
                                   <%= item.sugar_comtent %>
                                </td> 
                                <td>
                                   <%= item.fat_level %>
                                </td> 
                                <td>
                                   <%= item.contains_nuts %>
                                </td> 
                                <td>
                                    <%= item.mixture %>
                                </td>
                                <td>
                                   <%= item.ingredients %>
                                </td> 
                                <td>
                                   <%= item.catergory %>
                                </td>
                             </tr>
                        <% else %>
                        <% end %>
                    <% end %>
                    
            </table>
        </div>
    </div>
</div>

app/views/layouts/_store_items.html.erb
<style>

ul {
    list-style: none;
}

li {
    float: left;
    margin-right: 5px;
    padding-right: 5px;
    border-right: 0.5px solid #3b2e18;
}

</style>

    <% j = 'juices' %>
    <% v = 'vegetables' %>
    <% f = 'fruits' %>

<nav class="item-nav">
    <ul class="small-links">
        <li> Show only:: </li>
        <li> <%= link_to j, :sort => j %> </li>
        <li> <%= link_to v, :sort => v %> </li>
        <li> <%= link_to f, :sort => f%> </li>
        <% if params[:sort] == 'juices' %>
            <li> >> </li>
            <li> Filter by: </li>
            <li> 
                <%= link_to 'low fat', :sort => 'juices', :filter => 'low fat'  %>
            </li>
            <li> 
                <%= link_to 'low sugar', :sort => 'juices', :filter => 'low sugar'  %>
            </li>
             <li> 
                <%= link_to 'no nuts/seeds', :sort => 'juices', :filter => 'no nuts'  %>
            </li>
        <% end %>
        

             

            
    </ul>
</nav>

app/views/layouts/_user_nav.html.erb
 
 <div class="row">
            <ul class="nav nav-pills pull-right small-links">
                
                <% if logged_in? %>
                   <li> <%= link_to 'Users', '#' %> </li>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"> </b>
                        </a>
                        <ul class="dropdown-menu">
                            <li> 
                                <%= link_to 'Change Settings', edit_user_url(@current_user)%>
                                <%= link_to 'Your Shopping Cart', cart_path %>
                                <%= link_to 'Log Out', logout_url %>
                            </li>
                        </ul>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Admin Options
                            </a>
                            <ul class="dropdown-menu">
                                <li> <%= link_to 'Add an Item', new_item_path %> </li>
                                <li> <%= link_to 'Juice Table', juice_table_path %> </li>
                                <li> <%= link_to 'Modify a Vegetable', '#'%> </li>
                                <li> <%= link_to 'User Index', users_path %> </li>
                            </ul>
                        </li>
                    </li>
                    
                    <% else %>
                        <li>
                            <%= link_to 'Log In', login_url %>
                        </li>
                        <li>
                            <%= link_to 'Register', new_user_url %>
                        </li>
                <% end %>
            </ul>
</div>

app/views/layouts/_veg_menu.html.erb
        <div class="row">
            <div class="col-xs-4">
                <ul class="nav nav-pills nav-stacked">
                    <li> <%= link_to 'Vegetables', vegetables_path %> </li>
                    <li> <%= link_to 'Fruits', fruits_path %> </li>
                    <li> <%= link_to 'Nuts/Seeds', fruits_path %> </li>
                    <li> <%= link_to 'Juices', juices_path %> </li>
                </ul>
            </div>
        </div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> | Veggie App </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <% if logged_in? %>
     <%= @current_user.name %>
    <% end %>
    <br />
    <% if logged_in? && current_user.admin? %>
        You have adminstrative powers
    <% end %>
    
    
    <div class="container con-mod">
    
      <%= render 'layouts/header' %>
      
      <%= render 'layouts/user_nav' %>
      
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      
      
      <!-- Yield main content -->
      <div class="row">
          <div class="col-xs-12">
              <%= yield %>
          </div>
      </div>
        <% if logged_in? && current_user.admin? %>
            <%= debug(params) if Rails.env.development? %>
        <% end %>
        
        <%= render '/layouts/footer' %>
        
      </div>

  </body>
</html>